### ISSUE TITLE
report a Exception during deploy

### ISSUE THREAD

**Issue by StawEndl** [YanjieZe/Improved-3D-Diffusion-Policy#9]
1. missing normalizer.fit(obs_dict, mode='limits', last_n_dims=2) before normalizer.normalize(obs_dict) in forward fuction. it will throw a Exception if do not add that.
2. i got this Exception:
Traceback (most recent call last):
  File "deploy.py", line 389, in <module>
    main()
  File "/home/ace/anaconda3/envs/pnp/lib/python3.8/site-packages/hydra/main.py", line 90, in decorated_main
    _run_hydra(
  File "/home/ace/anaconda3/envs/pnp/lib/python3.8/site-packages/hydra/_internal/utils.py", line 389, in _run_hydra
    _run_app(
  File "/home/ace/anaconda3/envs/pnp/lib/python3.8/site-packages/hydra/_internal/utils.py", line 452, in _run_app
    run_and_report(
  File "/home/ace/anaconda3/envs/pnp/lib/python3.8/site-packages/hydra/_internal/utils.py", line 216, in run_and_report
    raise ex
  File "/home/ace/anaconda3/envs/pnp/lib/python3.8/site-packages/hydra/_internal/utils.py", line 213, in run_and_report
    return func()
  File "/home/ace/anaconda3/envs/pnp/lib/python3.8/site-packages/hydra/_internal/utils.py", line 453, in <lambda>
    lambda: hydra.run(
  File "/home/ace/anaconda3/envs/pnp/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/home/ace/anaconda3/envs/pnp/lib/python3.8/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/home/ace/anaconda3/envs/pnp/lib/python3.8/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "deploy.py", line 354, in main
    action = policy(obs_dict)[0]
  File "/home/ace/anaconda3/envs/pnp/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ace/codeM/Improved-3D-Diffusion-Policy-main/Improved-3D-Diffusion-Policy/diffusion_policy_3d/policy/diffusion_pointcloud_policy.py", line 179, in forward
    action_pred = self.normalizer['action'].unnormalize(naction_pred)
  File "/home/ace/codeM/Improved-3D-Diffusion-Policy-main/Improved-3D-Diffusion-Policy/diffusion_policy_3d/model/common/normalizer.py", line 50, in __getitem__
    return SingleFieldLinearNormalizer(self.params_dict[key])
  File "/home/ace/anaconda3/envs/pnp/lib/python3.8/site-packages/torch/nn/modules/container.py", line 738, in __getitem__
    return getattr(self, attr)
  File "/home/ace/anaconda3/envs/pnp/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'ParameterDict' object has no attribute 'action'

because, when normalizer.fit(obs_dict, mode='limits', last_n_dims=2), obs_dict have no action data. 
how to fix it?

**Comment by YanjieZe** [comment]
Hi, this seems to be the checkpoint problem. Have you successfully trained/saved the checkpoint?

**Comment by StawEndl** [comment]
> Hi, this seems to be the checkpoint problem. Have you successfully trained/saved the checkpoint?

i used checkpoints from your google drive. 

![image](https://github.com/user-attachments/assets/5418af96-1bd9-4b60-88cd-b89424570873)

**Comment by YanjieZe** [comment]
I see. Then that might be because the version of this checkpoint does not match the current cleaned version. I think these checkpoints are trained for the paper version and later I do a clean on current code, so there might be some mismatch. Could you try to train on the released data?

**Comment by StawEndl** [comment]
> I see. Then that might be because the version of this checkpoint does not match the current cleaned version. I think these checkpoints are trained for the paper version and later I do a clean on current code, so there might be some mismatch. Could you try to train on the released data?

OK, thanks. i try to train now.

**Comment by YanjieZe** [comment]
Sounds good
